name: Dispatcher
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  dispatch:
    name: Dispatch
    env:
      PACKAGES_TO_UPGRADE: ${{ needs.run_publish.outputs.packages }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo: ['receiver-demo']
    timeout-minutes: 5
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.AUTH_TOKEN }}
          repository: ${{ matrix.repo }}
          event-type: my-event
